### ISSUE TITLE
Is it possible to disable dragging for certain children nodes of the tree?

### ISSUE THREAD

**Issue by Phazia** [Shaddix/dnd-kit-sortable-tree#11]
As title says, it would be handy if there was a way to disable sorting on a child node. I know you can pass in true to disableSorting in the Sortable Tree root, but I wasn't able to disable sorting on children.

SimpleTreeItemWrapper seems to have a disableSorting property; explicitly setting it to true (instead of implicitly via the root) doesn't do anything, so I'm assuming it's meant to be read only.

**Comment by Shaddix** [comment]
you could add `disableSorting` property to `TreeItem` to disable it from being sorted/dragged.
Available since 0.1.51

**Comment by Phazia** [comment]
Hmm. Tried applying that property as a prop in the `SimpleTreeWrapper` to no avail. It appears that when console logging the props object, it's undefined and getting reset to undefined on each render. Any ideas why?

**Comment by huchaolin** [comment]
> Hmm. Tried applying that property as a prop in the `SimpleTreeWrapper` to no avail. It appears that when console logging the props object, it's undefined and getting reset to undefined on each render. Any ideas why?

may you need write is as follow:
    <SimpleTreeItemWrapper {...props} disableSorting={props.item.disableSorting} ref={ref}>
