### ISSUE TITLE
While changing the input field state from onchange its focusing out

### ISSUE THREAD

**Issue by reshin-pulapaddy** [Shaddix/dnd-kit-sortable-tree#13]
While changing the input field state from onchange it's focusing out, 
I can't type continuously

 <SimpleTreeItemWrapper {...props} ref={ref}>
            <h3>{res}</h3>
            <input
              value={sample || " "}
              onChange={(e) => {
                e.target.focus();
                setSample(e.target.value);
              }}
            ></input>
          </SimpleTreeItemWrapper>

**Comment by Shaddix** [comment]
Hi! Could you please provide a repro of the issue you are facing?

I tried to put it up here: https://playcode.io/1032571 but typing in the input is no issue there for me

**Comment by Shaddix** [comment]
I'm closing this one, since there's no actual repro.

Feel free to reopen with more details!
