### ISSUE TITLE
Manual Toggle?

### ISSUE THREAD

**Issue by lorkel** [Shaddix/dnd-kit-sortable-tree#15]
Is there a way to move the toggle to a specific child element of the SimpleTreeItemWrapper (similar to manualDrag)? I have an instance where I need to both be able to toggle and select each item.

Edited to add: if I add e.stopPropagation to the button I can override it, but wondering if there's something built-in. Thank you!

**Comment by Shaddix** [comment]
Hi! Sorry for a huge delay.. :)

You could do something like the following:
```
<SimpleTreeItemWrapper
      {...props}
      ref={ref}
      hideCollapseButton={true}
      disableCollapseOnItemClick={true}
    >
      
      {props.childCount && (
        <button onClick={props.onCollapse}>
          {props.collapsed ? 'expand' : 'collapse'}
        </button>
      )}
```
That is, pass `hideCollapseButton=true` and `disableCollapseOnItemClick=true` to the Wrapper, and draw the collapse/expand button manually

**Comment by Shaddix** [comment]
I hope this is resolved, feel free to reopen if it doesn't
