### ISSUE TITLE
On drag end item goes back

### ISSUE THREAD

**Issue by matv99v** [Shaddix/dnd-kit-sortable-tree#16]
When dragging any item and releasing mouse, it goes back to initial state but after that appears at proper position. 
[ScreenBug.webm](https://user-images.githubusercontent.com/12632592/228036636-941f544d-93ec-4617-8264-2b11eb063524.webm)

Reproducible via [playcode](https://playcode.io/1032571)

**Comment by Shaddix** [comment]
I hope this is resolved, feel free to reopen if it doesn't :)
