### ISSUE TITLE
depth property is not working

### ISSUE THREAD

**Issue by msunnyC23** [Shaddix/dnd-kit-sortable-tree#17]
How can we prevent folder moving inside to another folder? but all other items are free to move around?
I tried depth property, but not showing any effect.

**Comment by Shaddix** [comment]
I've adjusted the `canHaveChildren` prop a little bit, maybe it will help.
You could check out an example:
https://github.com/Shaddix/dnd-kit-sortable-tree/blob/42d4a79eba603c43168fd14420f405f113a709ee/stories/Simple.stories.tsx#L109

**Comment by msunnyC23** [comment]
working now.
as I can check for dragItem.canHaveChildren boolean or not. thank you
