### ISSUE TITLE
pointerSensorOptions

### ISSUE THREAD

**Issue by maxhudson** [Shaddix/dnd-kit-sortable-tree#18]
I wanted to document this here since it was helpful and I didn't see any mention here.

These are the default mouse event options:

```jsx
pointerSensorOptions={{
  activationConstraint: {
    distance: 10
  }
}}
```

I found this to be far more responsive feeling - presumably 10 is the default to avoid clicks that are accidentally drags to be mistaken for drags, but 10 is quite a distance in terms of how responsive it feels. Adjusting the value may be helpful:

```jsx
pointerSensorOptions={{
  activationConstraint: {
    distance: 3
  }
}}
```

**Comment by Shaddix** [comment]
Thanks! I changed the defaults and documented that in the Readme
