### ISSUE TITLE
disable dropanimation

### ISSUE THREAD

**Issue by maxhudson** [Shaddix/dnd-kit-sortable-tree#19]
I'm hoping to disable the animation that happens upon dropping an item, as it tends to be a bit buggy and feels unnecessary since the user has already dropped the item and probably expects to now see it stay where they dropped it (rather than jumping back to it's previous position and then to it's new position again).

I tried passing the following prop, but it had no effect:

```jsx
      dropAnimation={{duration: 0, easing: "ease"}}
```

line 279 in the implementation here: https://github.com/Shaddix/dnd-kit-sortable-tree/blob/master/src/SortableTree.tsx

```
          <DragOverlay
            dropAnimation={dropAnimation ?? dropAnimationDefaultConfig}
          >
```

It looks like it should work, but for some reason it doesn't seem to have any effect.

**Comment by Shaddix** [comment]
please try updating to [0.1.65](https://www.npmjs.com/package/dnd-kit-sortable-tree/v/0.1.65) and pass `null` to `dropAnimation`:
```
<DragOverlay dropAnimation={null}>
```

**Comment by konrad-gerlach** [comment]
I still have the issue after updating to 0.1.65 . The dropped items teleport back to their original position and then move to their new position.
`<SortableTree
              items={treeItems}
              onItemsChanged={updateRenderingOrder}
              TreeItemComponent={TreeItemComponent}
              dropAnimation={null}
            />`

**Comment by Shaddix** [comment]
(added to the FAQ in README):
If you want to [disable animation completely](https://shaddix.github.io/dnd-kit-sortable-tree/?path=/story/simple--no-drop-animation), you need to do the following:
1. Pass null as dropAnimation prop (this disables the actual 'drop' animation for the Node that was dragged).
1. Pass { animateLayoutChanges: () => false } to sortableProps (this disables the animation of all other nodes that were not dragged)

**Comment by Shaddix** [comment]
I'm closing the issue, feel free to reopen if something doesn't work

**Comment by konrad-gerlach** [comment]
Thanks a lot for the solution! The UI still seems a little buggy though, as for a split second one can sometimes see the item teleporting to its new position, which looks somewhat weird.

**Comment by maxhudson** [comment]
I've found that updating to the latest version of dnd-kit-sortable-tree does result in the animation being disabled properly - but unfortunately as konrad-gerlach is saying there is still a visual glitch.

I believe the transform that's being applied while dragging gets removed on drop, so there's a 1 frame/processor-tick delay until setState(changedItems) resolves on the next render.

Video here:

https://github.com/Shaddix/dnd-kit-sortable-tree/assets/7915687/88d565f0-4697-4fbf-af8f-9ba302d92339

Hoping that can be resolved as well, but thank you for the animation fix!

**Comment by maxhudson** [comment]
Looks like I'm not able to reopen this issue, so going to create a new one!
