### ISSUE TITLE
how to keep original place of element while dragging?

### ISSUE THREAD

**Issue by terlan4** [Shaddix/dnd-kit-sortable-tree#20]
So, when dragging starts, active element and its children gets deleted from DOM and we are left with ghost. However I would love to still keep active element in its place while trying to find a new place with its ghost.

I copied src folder to my project so I can make changes freely, played with CSS, then realized that it is actually happen via the code.
I couldn't get what I want without breaking functionality. Could you please help?

This is what I want to achieve - preserving space of element while dragging (on the video, element has space but not its content. I would like to preserve it together with content too)

https://github.com/Shaddix/dnd-kit-sortable-tree/assets/138553763/7208e8e4-067c-41d8-a387-de97dadf0ac0

**Comment by terlan4** [comment]
Actually better example to what I want is this: 

https://github.com/Shaddix/dnd-kit-sortable-tree/assets/138553763/f85ebc68-e989-42b3-bcb0-4cca835d5871

**Comment by Shaddix** [comment]
Yep, it totally makes sense to have something like this built-in. I'm gonna check if/how it's better to do this.
In the meantime, you could try passing an empty styles to e.g. <SimpleTreeItemWrapper {...props} **style={{}}** ref={ref}>:
```
        <SimpleTreeItemWrapper {...props} style={{}} ref={ref}>
          {/* HERE GOES THE ACTUAL CONTENT OF YOUR COMPONENT */}
          <div>{props.item.id} -00</div>
        </SimpleTreeItemWrapper>
```

**Comment by Shaddix** [comment]
you could try using `keepGhostInPlace`: you could set this to true to keep the Node that you are dragging in it's original place in a Tree. Check [VSCode](https://shaddix.github.io/dnd-kit-sortable-tree/?path=/story/simple--vs-code-like) sample to see it in action.

**Comment by terlan4** [comment]
Hi, Shaddix. I've also tried to play with styles before in similar way and got the same issue as that vscode sample. Turning off styles also turns off indentation while dragging so we can't tell whether it is indented or not.

![image](https://github.com/Shaddix/dnd-kit-sortable-tree/assets/138553763/79a3023f-4b79-4dcf-80a7-c2eb285e3eb5)

**Comment by Shaddix** [comment]
ok, I see. In this mode you'd probably want to always put the item inside the hovered node, right?

**Comment by terlan4** [comment]
No I would love to have notion like behavior as I shared on the second video. Hover puts inside, and border top/bottom puts before or after the node.

**Comment by Shaddix** [comment]
I'm gonna play a little bit and might add some settings that could potentially help.

But in general, it seems to me that you have specific requirements, that I might not be able to easily put inside the lib. You might be better off using dnd-kit directly.
Or at least, for this 'border top/bottom' behavior you might want to use your own `collisionDetection` from `dndContextProps`.

Though, if you see an easy way to do what you are after within this lib, the PR is always welcome!

**Comment by Shaddix** [comment]
I made some fixes for that `keepGhostInPlace` mode, and also provided `isOverParent` prop to `TreeItemComponent`.
I know it probably doesn't help you, I post it here rather for a future reference

**Comment by Shaddix** [comment]
I'm closing this one, since no work is currently planned for the issue.
Feel free to reopen or create new issues/pull requests!
