### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by cdes** [Shaddix/dnd-kit-sortable-tree#21]
I've been testing the package and discovered that the size of tree state will grow incredibly quick.  I've used object-sizeof to get the size of the tree and as you can see in the video, it gets crazy quickly.

https://github.com/Shaddix/dnd-kit-sortable-tree/assets/1207863/ee820dba-cfad-442c-9114-77c65e7c8dcd

Here's a playcode to show the issue (see the console):

https://playcode.io/1532895

**Comment by Shaddix** [comment]
Thanks for reporting the issue!
Will take a look coming days

**Comment by Shaddix** [comment]
this sems to be fixed, could you please try with the latest version?

**Comment by cdes** [comment]
Awesome! I'ts fixed now.
Had to use CodeSandbox because PlayCode can't seem to find and install versions greater than 0.1.58

https://codesandbox.io/s/dnd-kit-sortable-tree-n5ppcc?file=/src/App.tsx
