### ISSUE TITLE
Lot of Warnings from default props

### ISSUE THREAD

**Issue by sseppo** [Shaddix/dnd-kit-sortable-tree#6]
With the basic example, I get lot of warnings to console, for example:
"Warning: React does not recognize the `childCount` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `childcount` instead. If you accidentally passed it from a parent component, remove it from the DOM element."

Similar warnings for other props like isLast, disableSorting etc. In a bit further implementation, still mainly very similar to basic example, same goes also with indentationWidth, wrapperRef, disableSelection, disableInteraction, handleProps

also getting:
"Warning: Received `false` for a non-boolean attribute `collapsed`."
"Warning: Received `false` for a non-boolean attribute `ghost`."
"Warning: Unknown event handler property `onCollapse`. It will be ignored."
"Warning: Unknown event handler property `onRemove`. It will be ignored."

They are warnings not errors, but anyway.

**Comment by Shaddix** [comment]
Thanks, I'm gonna check them out and eliminate coming days

**Comment by Shaddix** [comment]
I pushed some changes, hopefully the warnings are resolved (at least there's no warnings in default samples now).

If you have some warnings related to `ghost` and `collapse` and you have defined your own analog of `SimpleTreeItemWrapper`, you shouldn't pass all your props down to the DOM element like below:
```
export const SimpleTreeItemWrapper = (props) => {
  return <div {...props}></div>
}
```

actually if you are building something specific for your project (not reusable in many projects) it's best to NOT pass whole `props` to DOM element at all. Only pass the props that you need (and in 90% of the cases you need none :)).

**Comment by Shaddix** [comment]
closing this one, since I hope it's resolved
