### ISSUE TITLE
Include extra data like drag source and destination

### ISSUE THREAD

**Issue by rabrenio** [Shaddix/dnd-kit-sortable-tree#8]
It would be helpful if we have data what item was dragged with its source and destination.
`{id: string, parent_id_source: string, parent_id_destination: string}`

We can use this if we want to know what item was changed.

Maybe we can pass this in `onItemsChanged`

**Comment by Shaddix** [comment]
yep, nice idea!
a PR would be great, otherwise I'm gonna add this myself during the next week

**Comment by Phazia** [comment]
This would be great. Is there a WIP @Shaddix to help out?

**Comment by Shaddix** [comment]
now there's a second argument in `onItemsChanged` callback describing the reason why items were changed.
Hope that suits the needs!
